CREATE USER store_usr WITH PASSWORD 'User@Store!25';
CREATE SCHEMA IF NOT EXISTS store AUTHORIZATION store_usr;

CREATE USER order_usr WITH PASSWORD 'User@Order!25';
CREATE SCHEMA IF NOT EXISTS "order" AUTHORIZATION order_usr;