apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  namespace: myteststore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: store
          image: myteststore/store:3.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: store-config
                  key: SERVER_PORT
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: store-config
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-secret-config
                  key: password
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: store-config
                  key: DATASOURCE_URL
          ports:
            - containerPort: 8080